CREATE TABLE [ZAMESTNANEC](
	[Zamestnanec_ID] [int] NOT NULL,
	[Jmeno] [nvarchar](100) NULL,
	[Prijmeni] [nvarchar](100) NULL,
	[Zdravotni_pojistovna] [nvarchar](100) NULL,
	[Mesto] [nvarchar](100) NULL
	);

CREATE TABLE [PRACOVNI_POZICE](
	[Pozice_ID] [int] NOT NULL,
	[Nazev] [nvarchar](100) NULL
	);

CREATE TABLE [ZAMESTNANEC_NA_PRACOVNI_POZICI](
	[Zamestnanec_ID] [int] NOT NULL,
	[Pozice_ID] [int] NOT NULL
	);

ALTER TABLE ZAMESTNANEC
	ADD CONSTRAINT PK_ZAMESTNANEC
		PRIMARY KEY (Zamestnanec_ID);

ALTER TABLE PRACOVNI_POZICE
	ADD CONSTRAINT PK_PRACOVNI_POZICE
		PRIMARY KEY (Pozice_ID);

ALTER TABLE ZAMESTNANEC_NA_PRACOVNI_POZICI
	ADD CONSTRAINT PK_ZAMESTNANEC_NA_PRACOVNI_POZICI
		PRIMARY KEY (Zamestnanec_ID,Pozice_ID);


ALTER TABLE ZAMESTNANEC_NA_PRACOVNI_POZICI 
	ADD CONSTRAINT FK_ZAMESTNANEC_NA_PRACOVNI_POZICI_ZAMESTNANEC_ID
		FOREIGN KEY (Zamestnanec_ID) 
			REFERENCES ZAMESTNANEC (Zamestnanec_ID);

ALTER TABLE ZAMESTNANEC_NA_PRACOVNI_POZICI 
	ADD CONSTRAINT FK_ZAMESTNANEC_NA_PRACOVNI_POZICI_POZICE_ID
		FOREIGN KEY (Pozice_ID) 
			REFERENCES PRACOVNI_POZICE (Pozice_ID);